{% set version = "0.2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tinysnapshot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tinysnapshot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tinysnapshot/tinysnapshot_{{ version }}.tar.gz
  sha256: 167bfeb4a9de0df04e74024ca152dadc7da506e4abf4efd0045fc2483d884da5

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-diffobj
    - r-magick >=2.7.4
    - r-tinytest >=1.4.1
  run:
    - r-base
    - r-diffobj
    - r-magick >=2.7.4
    - r-tinytest >=1.4.1

test:
  commands:
    - $R -e "library('tinysnapshot')"           # [not win]
    - "\"%R%\" -e \"library('tinysnapshot')\""  # [win]

about:
  home: https://github.com/vincentarelbundock/tinysnapshot
  license: GPL-3.0-or-later
  summary: Snapshots for unit tests using the 'tinytest' framework for R. Includes expectations to test base R and 'ggplot2' plots as well as console output from print().
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
